
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {

    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }



  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAulZfgU7Y1m6ImbBqXDm0OYkXKkFSZBZQ',
    appId: '1:16271199834:android:84ac62861a1681cd49b263',
    messagingSenderId: '416271199834',
    projectId: 'mykalori-app',
    databaseURL: 'https://mykalori-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mykalori-app.appspot.com',
  );




}
